In [ ]:
import json
from matplotlib import pyplot as plt
from collections import defaultdict
from sklearn import linear_model
import numpy as np
import random
import gzip
import math
# !pip install urllib
# from urllib import urlopen


In [ ]:
def assertFloat(x): # Checks that an answer is a float
    assert type(float(x)) == float

def assertFloatList(items, N):
    assert len(items) == N
    assert [type(float(x)) for x in items] == [float]*N

#Regression

## Q1

In [ ]:
f = gzip.open("young_adult_10000.json.gz")
dataset = []
for l in f:
    dataset.append(json.loads(l))

In [ ]:
dataset[0]


{'user_id': '8842281e1d1347389f2ab93d60773d4d',
 'book_id': '2767052',
 'review_id': '248c011811e945eca861b5c31a549291',
 'rating': 5,
 'review_text': "I cracked and finally picked this up. Very enjoyable quick read - couldn't put it down - it was like crack. \n I'm a bit bothered by the lack of backstory of how Panem and the Hunger Games come about. It is just kind of explained away in a few paragraphs and we are left to accept this very strange world where teenagers are pitted into an arena each year to kill each other? I was expecting it because I've seen Battle Royale, but I would have appreciated knowing more of the backstory of how the world could have come into such a odd state. \n I suppose what makes a book like this interesting is thinking about the strategy of it all. The players are going to be statistically encouraged to band together because they will last longer that way, but by definition of course any partnership will be broken, and the drama of how that unfolds is alw

In [ ]:
print(dataset[i]['review_text'].count('!') for i in range(10))

<generator object <genexpr> at 0x7ff8019a16d0>


In [ ]:
def feature(datum):
  feat = [1]
  #feat.append(datum['user/ageInSeconds'])
  feat.append(datum['review_text'].count('!'))
  return feat

In [ ]:
# tmpArrExcl = []
# tmpArrExcl = [[1]]*len(dataset)
# for i in range(len(dataset)):
#   tmpArrExcl[i].append(dataset[i]['review_text'].count('!'))
tmpArrExcl = [feature(d) for d in dataset]

In [ ]:
tmpArrExcl[:10]

[[1, 0],
 [1, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 4],
 [1, 2],
 [1, 1],
 [1, 0]]

In [ ]:
ratings = []
for i in range(len(dataset)):
  ratings.append(dataset[i]["rating"])

In [ ]:
ratings[:10]

[5, 5, 4, 2, 5, 5, 5, 5, 5, 5]

In [ ]:
# tmpArrExcl = np.array(tmpArrExcl)
# X = tmpArrExcl.reshape(-1,1)
# X[:10]

In [ ]:
X = tmpArrExcl

ratings = np.array(ratings)
y = ratings.reshape(-1,1)
y[:10]

array([[5],
       [5],
       [4],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5]])

In [ ]:
theta,residuals,rank,s = numpy.linalg.lstsq(X, y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [ ]:
print(theta)

[[3.68853304]
 [0.07109019]]


In [ ]:
y_pred = np.dot(X, theta)

MSE = ((y - y_pred)**2).mean()
print(MSE)

1.5231747404538287


## Q2

In [ ]:
def feature(datum):
  feat = [1]
  feat.append(len(datum['review_text']))
  
  feat.append(datum['review_text'].count('!'))
  return feat

In [ ]:
X = [feature(d) for d in dataset]

In [ ]:
X[:10]

[[1, 1326, 0],
 [1, 224, 1],
 [1, 118, 0],
 [1, 1952, 0],
 [1, 554, 0],
 [1, 486, 0],
 [1, 257, 4],
 [1, 10, 2],
 [1, 31, 1],
 [1, 62, 0]]

In [ ]:
theta,residuals,rank,s = numpy.linalg.lstsq(X, y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [ ]:
theta

array([[ 3.71751281e+00],
       [-4.12150653e-05],
       [ 7.52759173e-02]])

In [ ]:
y_pred = np.dot(X, theta)

MSE = ((y - y_pred)**2).mean()
print(MSE)

1.5214029246165832


## Q3

In [ ]:
def feature(datum,i):
  feat = [1]
  for j in range(1,i+1):
    feat.append((datum['review_text'].count('!'))**j)
  return feat

In [ ]:
for i in range(1,6):
  X = [feature(d,i) for d in dataset]
  # print(X[:10])
  theta,residuals,rank,s = numpy.linalg.lstsq(X, y)
  y_pred = np.dot(X, theta)
  MSE = ((y - y_pred)**2).mean()
  print("MSE",i,MSE)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


MSE 1 1.5231747404538287
MSE 2 1.5046686106250915
MSE 3 1.496684551517923
MSE 4 1.490447730223069
MSE 5 1.4896106953961648


In [ ]:
X[:10]

[[1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0],
 [1, 4, 16, 64, 256, 1024],
 [1, 2, 4, 8, 16, 32],
 [1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0]]

In [ ]:
type(dataset)

list

##Q4

In [ ]:
d_train = dataset[:len(dataset)//2]
d_test = dataset[(len(dataset)//2)+1:]
y_train = y[:len(y)//2]
y_test = y[(len(y)//2)+1:]

In [ ]:
for i in range(1,6):
  X_train = [feature(d,i) for d in d_train]
  X_test = [feature(d,i) for d in d_test]
  # print(X[:10])
  theta,residuals,rank,s = numpy.linalg.lstsq(X_train, y_train)
  y_pred = np.dot(X_test, theta)
  MSE = ((y_test - y_pred)**2).mean()
  print("MSE",i,MSE)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """


MSE 1 1.5246142562231482
MSE 2 1.4974739784895592
MSE 3 1.485426396997915
MSE 4 1.4765005973122816
MSE 5 1.4807263291580128


## Q5

In [ ]:
import scipy.optimize

In [ ]:
def MAE(theta0):
  # we will optimize the MAE function based on theta0 which with no other features is the final yPred.
  sumi = 0
  for i in range(len(y_test)):
    sumi += abs(theta0-y_test[i])
  sumi = sumi/len(y_test)
  return sumi


In [ ]:
guess = [0]
ans = scipy.optimize.minimize(MAE,guess)
print(ans)

      fun: 0.9067813572205767
 hess_inv: array([[1.09301531]])
      jac: array([0.20584331])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 138
      nit: 3
     njev: 63
   status: 2
  success: False
        x: array([4.])


In [ ]:
theta0 = 4.0
ans = MAE(theta0)

In [ ]:
print(ans)

[0.90678136]


# Classification

## Q6

In [ ]:
from urllib.request import urlopen
def parseDataFromURL(fname):
  for l in urlopen(fname):
    yield eval(l)

In [ ]:
data = list(parseDataFromURL("http://cseweb.ucsd.edu/classes/fa19/cse258-a/data/beer_50000.json"))

In [ ]:
data[1000]

{'review/appearance': 2.0,
 'beer/style': 'Light Lager',
 'review/palate': 2.0,
 'review/taste': 2.0,
 'beer/name': 'Amstel Light',
 'review/timeUnix': 1236554249,
 'user/gender': 'Male',
 'beer/ABV': 3.5,
 'beer/beerId': '436',
 'beer/brewerId': '163',
 'review/timeStruct': {'isdst': 0,
  'mday': 8,
  'hour': 23,
  'min': 17,
  'sec': 29,
  'mon': 3,
  'year': 2009,
  'yday': 67,
  'wday': 6},
 'review/overall': 1.5,
 'review/text': 'The color of chardonnay with about as much head as a glass of wine.\t\tAroma is initially a bitter skunky funk, some grassy straw notes, but if you concentrate you can pick out some bready honey malt lying way beneath.\t\tFlavor is similar to the nose, initially skunky, but some notes of corn and honey malt emerge as it rolls through the mouth.\t\tMouthfeel is slick and watery, but finishes tingly, very crisp. Very low drinkability. I know a lot of people like this as a low calorie lighter import, but there really is not much flavor, and what flavor is th

In [ ]:
dataset = [d for d in data if 'user/gender' in d]

In [ ]:
dataset[0]

{'review/appearance': 4.0,
 'beer/style': 'American Double / Imperial IPA',
 'review/palate': 4.0,
 'review/taste': 4.5,
 'beer/name': 'Cauldron DIPA',
 'review/timeUnix': 1293735206,
 'user/gender': 'Male',
 'user/birthdayRaw': 'Jun 16, 1901',
 'beer/ABV': 7.7,
 'beer/beerId': '64883',
 'user/birthdayUnix': -2163081600,
 'beer/brewerId': '1075',
 'review/timeStruct': {'isdst': 0,
  'mday': 30,
  'hour': 18,
  'min': 53,
  'sec': 26,
  'mon': 12,
  'year': 2010,
  'yday': 364,
  'wday': 3},
 'user/ageInSeconds': 3581417047,
 'review/overall': 4.0,
 'review/text': "According to the website, the style for the Caldera Cauldron changes every year. The current release is a DIPA, which frankly is the only cauldron I'm familiar with (it was an IPA/DIPA the last time I ordered a cauldron at the horsebrass several years back). In any event... at the Horse Brass yesterday.\t\tThe beer pours an orange copper color with good head retention and lacing. The nose is all hoppy IPA goodness, showcasing

In [ ]:
len(dataset)

20403

In [ ]:
# checing of only male and female exist
c = 0
for i in range(len(dataset)):
  if(dataset[i]['user/gender'] == 'Male') or (dataset[i]['user/gender'] == 'Female'):
    c+=1
print(c)

20403


### Hot encode

In [ ]:
for i in range(len(dataset)):
  if(dataset[i]['user/gender'] == 'Male'):
    dataset[i]['user/gender'] = 0
  else:
    dataset[i]['user/gender'] = 1

In [ ]:
dataset[21]


{'review/appearance': 4.0,
 'beer/style': 'American Pale Ale (APA)',
 'review/palate': 3.5,
 'review/taste': 4.0,
 'beer/name': 'Caldera Pale Ale',
 'review/timeUnix': 1249847121,
 'user/gender': 1,
 'user/birthdayRaw': 'Sep 2, 1975',
 'beer/ABV': 5.5,
 'beer/beerId': '25414',
 'user/birthdayUnix': 178873200,
 'beer/brewerId': '1075',
 'review/timeStruct': {'isdst': 0,
  'mday': 9,
  'hour': 19,
  'min': 45,
  'sec': 21,
  'mon': 8,
  'year': 2009,
  'yday': 221,
  'wday': 6},
 'user/ageInSeconds': 1239462247,
 'review/overall': 4.5,
 'review/text': "Received this can through Beer Powerball. I am really sorry that I don't know who sent it, my brother is keeping those records, but THANK YOU!!\t\tPours with a nice half centimeter white fluffy head on a glass of dark straw-colored beer. Smells of citrusy hoppy goodness and oddly, a little like soap. Mouthfeel is very pleasant as is taste. \t\tThis is a nice drinking beer. It's not blow you away with over-the-top flavor. It's a well-balanc

### Classification

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
def feature(datum):
  feat = [1]
  feat.append(datum['review/text'].count('!'))
  return feat

In [ ]:
X = [feature(d) for d in dataset]

In [ ]:
X[:10]

[[1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 1],
 [1, 1],
 [1, 0]]

In [ ]:
def labell(datum):
  feat = []
  feat.append(datum['user/gender'])
  return feat

In [ ]:
y = [labell(d)[0] for d in dataset]

In [ ]:
y[:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
classModel = LogisticRegression().fit(X,y)

In [ ]:
y_pred = classModel.predict(X)

In [ ]:
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
Tp,Tn,Fp,Fn = 0,0,0,0
for i in range(len(y)):
  if y[i] == y_pred[i] == 1: # female
    Tp+=1
  elif y[i] == 1 and y_pred[i] == 0:
    Fn+=1
  elif y[i] == y_pred[i] == 0: # male
    Tn+=1
  else:
    Fp+=1

print(Tp,Tn,Fp,Fn)
  
  

0 20095 0 308


In [ ]:
from sklearn.metrics import balanced_accuracy_score

In [ ]:
balanced_accuracy_score(y,y_pred)

0.5

In [ ]:
BER = 1 - 0.5 * (Tp / (Tp + Fn) + Tn / (Tn + Fp))
print(BER)

0.5


## Q7

In [ ]:
classModel = LogisticRegression(class_weight="balanced").fit(X,y)

In [ ]:
y_pred = classModel.predict(X)

In [ ]:
Tp,Tn,Fp,Fn = 0,0,0,0
for i in range(len(y)):
  if y[i] == y_pred[i] == 1: # female
    Tp+=1
  elif y[i] == 1 and y_pred[i] == 0:
    Fn+=1
  elif y[i] == y_pred[i] == 0: # male
    Tn+=1
  else:
    Fp+=1

print(Tp,Tn,Fp,Fn)
  
  

88 16332 3763 220


In [ ]:
balanced_accuracy_score(y,y_pred)
# uploading old value cause this agains balances it, waste

0.5492268865744855

In [ ]:
BER = 1 - 0.5 * (Tp / (Tp + Fn) + Tn / (Tn + Fp))
print(BER)

0.4507731134255145


## Q8

In [ ]:
tmp = y_pred

In [ ]:
k = [1, 10, 100, 1000, 10000]
sumi = 0
for i in k:
  sumi = 0
  for j in range(i):
    if y[j] == y_pred[j] == 1: # female
      sumi+=y_pred[j]
    elif y[j] == y_pred[j] == 0: # male
      sumi+=y_pred[j]
  sumi/=i
  print("precision@",i,sumi)

precision@ 1 0.0
precision@ 10 0.0
precision@ 100 0.01
precision@ 1000 0.003
precision@ 10000 0.004


### Precision@K using weights(confidence)

In [ ]:
scores = classModel.decision_function(X)
scores = list(zip(scores, y))
scores.sort(reverse=True)
sortedScore = [i[1] for i in scores]
precisionlist = []
for i in k:
  print("precision@",i,sum(sortedScore[:i])/i)

# print(precisionlist)

precision@ 1 0.0
precision@ 10 0.0
precision@ 100 0.03
precision@ 1000 0.033
precision@ 10000 0.0308
